[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "LEITmotifs"
version = "0.1"
description = ""
authors = [
  { name = "Francesco Pio Monaco", email = "francescopio.monaco@unipd.it" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU AGPLv3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
  "requests>2",
  "numpy",
  "numba",
  "matplotlib",
  "seaborn",
  "scipy",
  "stumpy",
]

[project.urls]
"Homepage" = "https://github.com/FrancescoMonaco/LEIT-motifs"
"Bug Tracker" = "https://github.com/FrancescoMonaco/LEIT-motifs/issues"

[tool.setuptools.packages.find]
where = ["source"]